set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_tri_i[0]}]
set_property PACKAGE_PIN T12 [get_ports {led_tri_o[1]}]
set_property PACKAGE_PIN U12 [get_ports {led_tri_o[0]}]
set_property PACKAGE_PIN M19 [get_ports {btn_tri_i[1]}]
set_property PACKAGE_PIN M20 [get_ports {btn_tri_i[0]}]
